/**
 * inference.h  —  Zero-dependency neural network inference for SofconNet.
 *
 * Include this header + weights.h (generated by tools/export_weights.py)
 * in your submission file.  No external libraries required.
 *
 * Architecture mirrors model/network.py exactly:
 *   Stem Conv(c_in→64, 3x3) + BN + ReLU
 *   5x ResBlock(64)
 *   Policy head: Conv(64→2,1x1)+BN+ReLU → FC(2*H*W → H*W) → Softmax
 *   Value  head: Conv(64→1,1x1)+BN+ReLU → FC(H*W→256)+ReLU → FC(256→1)+Tanh
 */

#pragma once
#include <cmath>
#include <cstring>
#include <algorithm>
#include <vector>
#include <cstdio>
#include <cstdlib>

#include "board.cpp"

using namespace game;


#if 1       //速度のため、本番で消えるアサート
#define ASSERT(cond, ...) \
    do { \
        if (!(cond)) { \
            std::fprintf(stderr, "Assert failed: %s (%s:%d)\n  ", \
                         #cond, __FILE__, __LINE__); \
            std::fprintf(stderr, __VA_ARGS__); \
            std::fprintf(stderr, "\n"); \
            std::abort(); \
        } \
    } while (0)
#else
#define ASSERT(cond, ...) ((void)0)
#endif


namespace nn {

// ------------------------------------------------------------------ //
//  Basic math helpers
// ------------------------------------------------------------------ //

static inline float relu(float x) { return x > 0.f ? x : 0.f; }
static inline float fast_tanh(float x) {
    // accurate enough for inference
    if (x >  4.f) return  1.f;
    if (x < -4.f) return -1.f;
    float x2 = x * x;
    return x * (27.f + x2) / (27.f + 9.f * x2);
}

// ------------------------------------------------------------------ //
//  Tensor helpers  (row-major, no heap except caller-provided buffers)
// ------------------------------------------------------------------ //

// out[oc, oh, ow] = sum_{ic,kh,kw} in[ic, oh+kh, ow+kw] * w[oc,ic,kh,kw] + b[oc]
// in_data : (C_in,  H,  W)
// w       : (C_out, C_in, kH, kW)
// b       : (C_out,) or nullptr
// out     : (C_out, H_out, W_out)  — caller allocates

//テンソル定義をしてみる。各テンソルは

//各テンソル


//4次元テンソルを作る.
//よくわからないのでまずバカみたいに作ってみます。


//vector等は使わないで、配列でnewだけにしておきます。もしくはポインタだけ指示して
class tensor
{
private:
    const float   * __p_arr;      //toku　これは、tensor_2dが並んでいるとみなします。
    int             __alt;        //先頭アドレスを変化させられるためのオフセット値です。（位置ずらすときに、いちいち新しいオブジェクトを作らなくていいように）
    tensor(floar* p_arr) : __p_arr(p_arr) , __alt(0){}
protected:
    //各テンソルのサイズ分のオフセットをさせる。(戻り値はその時の左上アドレス)
    void     _alt(int n){
        __alt = n*size();
    }

public:
    int size()const =0;         //自身の配列上のサイズを返す。
    //基準ポイントをそれぞれ計算したい場所に応じて変化させられるように
    //各テンソルの左上アドレスを返す
    float *p_head()const{
        return __p_arr + __ofs;
    }


};
class tensor_2d :   public tensor
{
    //shape
    const int __W;
    const int __H;
protected:
public:
    tensor_2d(float *p_arr , int h,int w):  tensor(p_arr) , __H(h) , __W(w){}

    //この二次元テンソルが並んでいるとして、n面目の先頭アドレスを返すようにします。
    int size(int n)const        {   return __W*__H;                 }
//  float *p_head_n(int n)const {   return  __p_arr + (n*size());   }    //とりあえず、
    //※convのpadding対応のために、ofsをもった場所を指示できるようにします。
    float dot(const tensor_2d &a , int x_ofs=0 , int y_ofs=0)const{
        float v=0.0;
        //dot積の範囲は、aに合わせます。
        for(int y=0 ; y < a.h ; ++y ){
            for(int x = 0  ; x < a.w  ; ++x){                   //aの範囲を全部、
                v += v(x+x_ofs,y+y_ofs) * a.v(x,y);             //自分の範囲は、ofs分ずらした位置
            }
        }
        return v;
    }
    //先頭位置をずらす
    tensor_2d &alt(int n){        tensor::_alt(n);        return *this;    }

    //このhsapeの配列へアクセスするような値を返す関数。[][]のような
    float v(int x,int y)const{        //p_headは好きな場所を指示する場合に使います。
        if(x<0||x>=w||y<0||y>=h){
            return 0;                   //範囲外は0とします。
        }
        return *( p_head() + (y *w * x));
        //                  ^^^^^^^^^^^
        //                  この平面がどこのオフセットかを自由に設定できる。（保証は呼び出し側で）
    }
}
//配列実体は内包しないで、アクセスヘルパーです。
class tensor_3d
{
    const int   __D;          //これが奥行。
protected:
public:    
    //3dテンソルが並んでいるとして、n番目の先頭アドレスを返す。
    int size()const{    __D * window_2d.size();    }
//  float *p_headn_n(int n){      }
    //この3dテンソルは、
    //      A():    9×15*15
    //      K():    9*3*3
    //paddingの処理も必要。
    tensor_3d(float *p_arr , int d , int h , int w) : tensor(p_arr),__D(d), window_2d(p_arr,h,w) {}

    //2次元テンソルを内包する。これは使いやすい窓として    
    tensor_2d   window_2d;    //2dテンソルを内包させてみる。2dテンソルが配列のように並んでいるとみる。

    //aの深さに合わせて、dotをとります。
    float dot(tensor_3d& a,int x_ofs=0,int y_ofs=0)const{
        float v=0.0;
        for(int z = 0 ; z < a.d ; ++z ){      //このZレイヤーの面のdot積を考える。aは左上から、スタート、自分自身は、どこの部分を
            //このテンソルのzの先頭
            v += window_2d.alt(z).dot( a.window_2d.alt(z) , x_ofs, y_ofs );
        }
        return v;
    }
    //先頭位置をずらす
    tensor_3d &alt(int n){        tensor::_alt(n);  return *this;   }
    //このテンソルが並んでいるとしてidx番目の3dテンソルなかの値を取り出す。
    float v(int x,int y ,int z)const{
        //範囲外はここで
        if(z < 0 || z >= d ){
            return 0.0;
        }
        return window_2d.alt(z).v(x,y);
    }
};

struct tensor_4d
{
    //
    tensor_3

};



static void conv2d(
    const float* in_data, int C_in,  int H,   int W,            //inputデータの情報     :  in_data  :  盤面15(H)×15(W)× 9のデータを表してます   tensor 1
    const float* w,       int C_out, int kH,  int kW,           //重みカーネルの情報    :   w       :   C_outは、16                            tensor 2
    const float* b,                                             //  バイアス    nullならばなし
    float* out,                                                 //  出力 tensor ( 15*15*16)
    int pad = 1, int stride = 1)                                //  padding を 1(in_dataの周りに0のパディングを付ける)  stride : カーネルのずらし量
{
    int H_out = (H + 2*pad - kH) / stride + 1;      //出力用テンソルの幅
    int W_out = (W + 2*pad - kW) / stride + 1;      //出力用テンソルの高

    for (int oc = 0; oc < C_out; ++oc) {                        //oc    出力テンソルの深さ
        for (int oh = 0; oh < H_out; ++oh) {                    //oh    出力テンソルの高さ
            for (int ow = 0; ow < W_out; ++ow) {                //ow    出力テンソルの幅
                float sum = b ? b[oc] : 0.f;                    //  b   バイアス

                for (int ic = 0; ic < C_in; ++ic) {                 //ic    入力テンソルの深さに対するループ
                    for (int kh = 0; kh < kH; ++kh) {                   //kh    0-カーネルの高さ
                        for (int kw = 0; kw < kW; ++kw) {               //kw    0-カーネルの幅
                            int ih = oh*stride - pad + kh;                  //  ih  :   出力カーネルの書き込み位置
                            int iw = ow*stride - pad + kw;                  //  iw  :   出力カーネルの書き込み位置
                            if (ih < 0 || ih >= H || iw < 0 || iw >= W) continue;       //ih,iw がカーネルの平面から、 外れている場合は、計算しない
                            int in_idx  = (ic*H + ih)*W + iw;                           //in_idx    :   入力データのidx
                            //
                            int w_idx   = ((oc*C_in + ic)*kH + kh)*kW + kw;             //w_idx     :   カーネルデータのidx
                            sum += in_data[in_idx] * w[w_idx];                              //sum : 
                        }
                    }
                }
                out[(oc*H_out + oh)*W_out + ow] = sum;
            }
        }
    }
}

// Batch-norm (inference mode, no running stats update)
// x, out: (C, H, W)  gamma/beta/mean/var: (C,)
static void batch_norm(
    const float* x, int C, int H, int W,
    const float* gamma, const float* beta,
    const float* running_mean, const float* running_var,
    float eps, float* out)
{
    int hw = H * W;
    for (int c = 0; c < C; ++c) {
        float scale = gamma[c] / std::sqrt(running_var[c] + eps);
        float shift = beta[c] - running_mean[c] * scale;
        const float* src = x   + c * hw;
        float*       dst = out + c * hw;
        for (int i = 0; i < hw; ++i)
            dst[i] = src[i] * scale + shift;
    }
}

// in-place relu on (C,H,W) tensor
static void relu_inplace(float* x, int n) {
    for (int i = 0; i < n; ++i) x[i] = relu(x[i]);
}

// residual add: out[i] += x[i], then relu
static void add_relu(float* out, const float* x, int n) {
    for (int i = 0; i < n; ++i) out[i] = relu(out[i] + x[i]);
}

// FC: out[j] = sum_i in_data[i]*w[j*in_features+i] + b[j]
static void linear(
    const float* in_data, int in_features,
    const float* w, const float* b,
    float* out, int out_features)
{
    for (int j = 0; j < out_features; ++j) {
        float s = b ? b[j] : 0.f;
        const float* row = w + j * in_features;
        for (int i = 0; i < in_features; ++i) s += in_data[i] * row[i];
        out[j] = s;
    }
}

static void softmax(float* x, int n) {
    float mx = *std::max_element(x, x+n);
    float sum = 0.f;
    for (int i = 0; i < n; ++i) { x[i] = std::exp(x[i] - mx); sum += x[i]; }
    for (int i = 0; i < n; ++i) x[i] /= sum;
}

// ------------------------------------------------------------------ //
//  Network config (must match training)
// ------------------------------------------------------------------ //
static const int CH    = 16;   // trunk channels
static const int NBLK  = 3;    // ResBlocks
static const float BN_EPS = 1e-5f;


// ------------------------------------------------------------------ //
//  Forward pass
//  board_input: (C_in, H, W) float array (caller fills)
//  policy_out : (H*W,) float  — softmax probabilities
//  value_out  : scalar float  — win estimate in (-1,1)
// ------------------------------------------------------------------ //
struct NetWeights {};  // weights are static globals in weights.h

void forward(const float* board_input, int C_in, int H, int W,
             const NetWeights& wt,
             float* policy_out, float& value_out);

}; // namespace sofcon_nn

/**
 * inference_impl.h  —  NetWeights struct + forward() implementation.
 *
 * Include AFTER weights.h:
 *   #include "weights.h"
 *   #include "inference.h"
 *   #include "inference_impl.h"
 *
 * weights.h is generated by tools/export_weights.py and contains
 * all float arrays with the naming convention:
 *   w_stem_0_weight, w_stem_1_weight, w_stem_1_bias, etc.
 */

#pragma once
#include "inference.h"
#include <vector>
#include <cstring>

namespace sofcon_nn {

// Scratch buffer pool (stack-like, avoids repeated malloc)
struct Scratch {
    std::vector<float> buf;
    Scratch(int n) : buf(n, 0.f) {}
    float* get(int offset = 0) { return buf.data() + offset; }
};

// ------------------------------------------------------------------ //
//  ResBlock forward
// ------------------------------------------------------------------ //
static void res_block_forward(
    const float* x, int C, int H, int W,
    // conv1 weight/BN params
    const float* c1w,
    const float* b1g, const float* b1b, const float* b1m, const float* b1v,
    // conv2 weight/BN params
    const float* c2w,
    const float* b2g, const float* b2b, const float* b2m, const float* b2v,
    float* out, float* tmp1, float* tmp2)
{
    int chw = C * H * W;

    // conv1 → BN1 → ReLU
    conv2d(x,    C, H, W, c1w, C, 3, 3, nullptr, tmp1);
    batch_norm(tmp1, C, H, W, b1g, b1b, b1m, b1v, BN_EPS, tmp2);
    relu_inplace(tmp2, chw);

    // conv2 → BN2
    conv2d(tmp2, C, H, W, c2w, C, 3, 3, nullptr, tmp1);
    batch_norm(tmp1, C, H, W, b2g, b2b, b2m, b2v, BN_EPS, out);

    // residual + ReLU
    add_relu(out, x, chw);
}

// ------------------------------------------------------------------ //
//  Full forward pass  (uses weights.h symbols directly)
// ------------------------------------------------------------------ //
//      board_input :   盤面
//      C_in        :   
void forward(const float* board_input, int C_in, int H, int W,
             const NetWeights& /*wt — unused, we use globals from weights.h*/,
             float* policy_out, float& value_out)
{
    //toku どういう構成かは、なんとなくわかった。
    //  input              1st layer                middle layer × 3                                output layer
    //15×15盤面s    →   9×9 の特徴周出×16   →   [ conv->BIN(正規化)-> + input -> Relu ----+-----+----(value head)-----> 全結合 -> tanh関数 -> スカラー値 ( -1 ～ 1 )  →　これをプレイヤー数に拡張か。
    //                                     ↑                                            ↓     |
    //                                     +--------------------<-----------------------+     |
    //                                                                                        |
    //                                                                                        +-----(policy head)----> 全結合 -> softmax関数 -> 各手に対する  確率分布 (合計 1)
    //
    //  loss　関数は、
    //                                                 →
    //                  l = Σ ( v_Θ(s_t) - z_t)^2    - π_t・log(p_Θ(s_t))
    //                      t   
    //                      ^^^^^^^^^^^^^^^^^^^^^^
    //                          v_Θ(s_t)    : 各手順での価値かな? 
    //                          z_t         : 各手順での勝敗か(-1 or 1)
    //
    //                                                ^^^^^^^^^^^^^^^^^^^^
    //                                                 pΘ(s_t):ベクトル       ：    盤面s_tでの、NNの出した方策。
    //                                                 π（ベクトル：手の数か） ：   MCTSの答え。（全手順分の、訪問ん回数を正規化したもの）
    //                                                  
    //                                                 →    
    //                      ↑価値判断の2乗誤差（の和）      ↑   MTCS(正解)×NNの出した方策の正しさ(正解×log(解答)：確率分布)　ベクトルの内席計算と同じ計算（各要素をかけて和を取る）
    //                                                        MCTSとNNの出した答えがあっていればいるほど、値が小さくなる。
    //                                                          ( ＝  NNの方策のただしさ：MCTSが正解ととらえる。)
    //                  (Simple Alpha Zero tutrial より)
    //


    //board_input   は、C_in × [H(15)][W(15)]の盤面データです。

    //  C_in    :       9が入る（board_inputの盤面の数)
    //  H,W     :       盤面の縦横サイズ
    //  CH      :       一番初めのconvで作られる小さいサイズの特徴データ（9×9 matrix）
    //  NBLK    :       中間層の層数
    //  BN_EPS  :       正規化の時の何か定数
    //static const int CH    = 16;   // trunk channels
    //static const int NBLK  = 3;    // ResBlocks
    //static const float BN_EPS = 1e-5f;

    int hw  = H * W;
    int chw = CH * hw;

    // allocate scratch
    std::vector<float> a(chw), b(chw), c(chw), d(chw);
    //------------------------------------------------------------------------------------------------------------------------
    //              各Vectorの先頭アドレス。
    //------------------------------------------------------------------------------------------------------------------------
    float* cur  = a.data();     //これはデータ配列の先頭アドレスを代入している。
    float* tmp1 = b. data();
    float* tmp2 = c.data();
    float* res  = d.data();

    // ---- Stem ----
    // Conv(C_in → CH, 3x3, pad=1)
    //------------------------------------------------------------------------------------------------------------------------
    //  input   →   16× (9×9)のconvを作る。
    //------------------------------------------------------------------------------------------------------------------------
    conv2d(board_input, C_in, H, W,
           w_stem_0_weight, CH, 3, 3, nullptr, tmp1);
    // BN + ReLU
    batch_norm(tmp1, CH, H, W,
               w_stem_1_weight, w_stem_1_bias,
               w_stem_1_running_mean, w_stem_1_running_var,
               BN_EPS, cur);
    relu_inplace(cur, chw);
    //

    // ---- ResBlocks ----
#define RES(i) \
    res_block_forward(cur, CH, H, W, \
        w_blocks_##i##_conv1_weight, \
        w_blocks_##i##_bn1_weight, w_blocks_##i##_bn1_bias, \
        w_blocks_##i##_bn1_running_mean, w_blocks_##i##_bn1_running_var, \
        w_blocks_##i##_conv2_weight, \
        w_blocks_##i##_bn2_weight, w_blocks_##i##_bn2_bias, \
        w_blocks_##i##_bn2_running_mean, w_blocks_##i##_bn2_running_var, \
        res, tmp1, tmp2); \
    std::swap(cur, res);

    RES(0) RES(1) RES(2)
#undef RES

    // ---- Policy head ----
    {
        std::vector<float> ph(2*hw);
        conv2d(cur, CH, H, W, w_policy_conv_weight, 2, 1, 1, nullptr, tmp1, 0, 1);
        batch_norm(tmp1, 2, H, W,
                   w_policy_bn_weight, w_policy_bn_bias,
                   w_policy_bn_running_mean, w_policy_bn_running_var,
                   BN_EPS, ph.data());
        relu_inplace(ph.data(), 2*hw);
        linear(ph.data(), 2*hw, w_policy_fc_weight, w_policy_fc_bias,
               policy_out, hw);
        softmax(policy_out, hw);
    }

    // ---- Value head ----
    {
        std::vector<float> vh(hw), vh2(256);
        conv2d(cur, CH, H, W, w_value_conv_weight, 1, 1, 1, nullptr, tmp1, 0, 1);
        batch_norm(tmp1, 1, H, W,
                   w_value_bn_weight, w_value_bn_bias,
                   w_value_bn_running_mean, w_value_bn_running_var,
                   BN_EPS, vh.data());
        relu_inplace(vh.data(), hw);
        linear(vh.data(), hw, w_value_fc1_weight, w_value_fc1_bias, vh2.data(), 256);
        relu_inplace(vh2.data(), 256);
        float vscalar;
        // read only value[0] = current player's win-prob (layout: [MAX_PLAYERS, 256])
        linear(vh2.data(), 256, w_value_fc2_weight, w_value_fc2_bias, &vscalar, 1);
        value_out = 1.0f / (1.0f + std::exp(-vscalar));  // sigmoid, matches Python
    }
}

//---------------------------------------------------------------------
//  最初の盤面を、ブロック種類によって、9種類の盤面に分解します。
//  [0]   :   壁だけ集めた
//  [1]   :   空きだけ集めた
//  [2]   :   必ず自分
//  [3]   :   他プレイヤー 1
//  [4]   :   他プレイヤー 2
//  [5]   :   他プレイヤー 3
//  [6]   :   他プレイヤー 4
//  [7]   :   これは空き（n_all_playrが6になってもできるように）→5人対戦のときは0
//  [8]   :   プレイヤー人数などの文脈を教えるためのデータする。
//----------------------------------------------------------------------
//         static float nn_input[9 * MAXN * MAXN];         //9画面分    →   outとして引数に入ります。
    static void board_to_nn_input(const board& b, float* out /*must 9×15×15 */) {
        const int hw = game::H_SIZ * game::W_SIZ;               //1盤面サイズ
        std::fill(out, out + (9 * hw), 0.f);                    //0でfillします。 9×盤面サイズ分
        for (int y = 0; y < game::H_SIZ ; ++y) {
            for (int x = 0; x < game::W_SIZ ; ++x) {            //
//                int idx = r * b.W + c;
                game::Pos p(x,y);
                int8_t cell = b._st[y][x];
                if (cell == WALL)  out[p.idx] = 1.f;     //壁は[0]
                if (cell == EMPTY) out[hw + p.idx] = 1.f; //空きは[1]
                //各プレイヤーの盤面を登録。cur_player基準で[2]-[7]まで入れていく。（）
                for (int k = 0; k < b.n_all_player && k < 6; ++k) {             //kは盤面のインデックスです。0がcur_playerとなるように
                    int pid = (b.cur_player - 1 + k) % b.n_all_player + 1;      //cur_playerが pid ==1 になるように,全プレイヤーの番号を作る。k=0,..,5です
                    if (cell == (int8_t)pid) out[(2 + k) * hw + p.idx] = 1.f;   //該当する盤面データ[k]1を書きます。
                }
            }
        }
        //盤面[8]は、プレイ人数などの情報を入れる。
        float np_norm = (float)(b.n_all_player - 1) / 5.f;     //プレイ人数を最大6人ならば  (0～5) / 5　で、 0.0 - 5.0までの間の値として、
        std::fill(out + 8 * hw, out + 9 * hw, np_norm);        //  盤面一面に置きます。（これは一つの特徴）
    }

};
// namespace sofcon_nn